"""add_feedback_fields

Revision ID: 35021535215b
Revises: 349197b67f44
Create Date: 2026-06-24 15:18:05.863350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35021535215b'
down_revision: Union[str, Sequence[str], None] = '349197b67f44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_feedbacks', sa.Column('improvements', sa.Text(), nullable=True))
    op.add_column('interview_feedbacks', sa.Column('ideal_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_feedbacks', 'ideal_answer')
    op.drop_column('interview_feedbacks', 'improvements')
    # ### end Alembic commands ###
