"""add interview types

Revision ID: 6a850e2c255f
Revises: 981d43437189
Create Date: 2026-06-10 12:20:50.553906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a850e2c255f'
down_revision: Union[str, Sequence[str], None] = '981d43437189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interview_types', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interview_types')
    # ### end Alembic commands ###
