"""Add question metadata

Revision ID: 8646ee25cb83
Revises: 8e8106792e41
Create Date: 2026-07-08 14:37:58.397708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8646ee25cb83'
down_revision: Union[str, Sequence[str], None] = '8e8106792e41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('time_complexity', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('space_complexity', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('interview_tips', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'interview_tips')
    op.drop_column('questions', 'space_complexity')
    op.drop_column('questions', 'time_complexity')
    # ### end Alembic commands ###
