"""Add company category

Revision ID: 8e8106792e41
Revises: e8155b7b4d66
Create Date: 2026-07-07 20:09:37.001288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e8106792e41'
down_revision: Union[str, Sequence[str], None] = 'e8155b7b4d66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "companies",
        sa.Column("category", sa.String(), nullable=True)
    )

    op.execute("""
        UPDATE companies
        SET category = 'Global Product'
        WHERE id IN (1,2,3,4)
    """)

    op.alter_column(
        "companies",
        "category",
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'category')
    # ### end Alembic commands ###
