"""update_resume_model

Revision ID: 99e41cd529a3
Revises: 2e6b37a45187
Create Date: 2026-06-22 13:43:53.639566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99e41cd529a3'
down_revision: Union[str, Sequence[str], None] = '2e6b37a45187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_url', sa.String(), nullable=True))
    op.drop_column('resumes', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('resumes', 'file_url')
    # ### end Alembic commands ###
