"""Drop old interview models

Revision ID: e4cf36ddece5
Revises: 09fe619d1b9b
Create Date: 2026-07-14 15:34:51.920435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4cf36ddece5'
down_revision: Union[str, Sequence[str], None] = '09fe619d1b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_answer_feedbacks_id'), table_name='interview_answer_feedbacks')
    op.drop_table('interview_answer_feedbacks')
    op.drop_index(op.f('ix_interview_feedbacks_id'), table_name='interview_feedbacks')
    op.drop_table('interview_feedbacks')
    op.drop_index(op.f('ix_session_configs_id'), table_name='session_configs')
    op.drop_table('session_configs')
    op.drop_index(op.f('ix_session_answers_id'), table_name='session_answers')
    op.drop_table('session_answers')
    op.drop_index(op.f('ix_interview_sessions_id'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_answers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('answer_text', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time_taken', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('session_answers_question_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('session_answers_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('session_answers_pkey'))
    )
    op.create_index(op.f('ix_session_answers_id'), 'session_answers', ['id'], unique=False)
    op.create_table('interview_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('interview_sessions_company_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('interview_sessions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_sessions_pkey'))
    )
    op.create_index(op.f('ix_interview_sessions_id'), 'interview_sessions', ['id'], unique=False)
    op.create_table('interview_answer_feedbacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('answer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('strengths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('improvements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ideal_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['session_answers.id'], name=op.f('interview_answer_feedbacks_answer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_answer_feedbacks_pkey'))
    )
    op.create_index(op.f('ix_interview_answer_feedbacks_id'), 'interview_answer_feedbacks', ['id'], unique=False)
    op.create_table('session_configs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('question_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_type_id'], ['question_types.id'], name=op.f('session_configs_question_type_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('session_configs_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('session_configs_pkey'))
    )
    op.create_index(op.f('ix_session_configs_id'), 'session_configs', ['id'], unique=False)
    op.create_table('interview_feedbacks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('improvements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ideal_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('strengths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('interview_feedbacks_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_feedbacks_pkey'))
    )
    op.create_index(op.f('ix_interview_feedbacks_id'), 'interview_feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###
