"""Add company profile fields

Revision ID: e8155b7b4d66
Revises: e09e16bf3955
Create Date: 2026-07-07 19:20:23.651803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8155b7b4d66'
down_revision: Union[str, Sequence[str], None] = 'e09e16bf3955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('logo', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('company_type', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('headquarters', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('founded', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('employees', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(), nullable=True))
    op.alter_column('companies', 'description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'employees')
    op.drop_column('companies', 'founded')
    op.drop_column('companies', 'headquarters')
    op.drop_column('companies', 'company_type')
    op.drop_column('companies', 'logo')
    # ### end Alembic commands ###
